name: Deploy AIML Server Prod Image
on:
  workflow_dispatch:

jobs:
  image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Cache turbo build setup
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          registry: us-chicago-1.ocir.io
          username: axhaeqbjwexc/${{ secrets.OCI_USER }}
          password: ${{ secrets.OCI_AUTH_TOKEN }}
      - name: Build image
        run: bun run deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEPLOY_MODE: "production"
          OCI_AUTH_TOKEN: ${{ secrets.OCI_AUTH_TOKEN }}
          OCI_USER: ${{ secrets.OCI_USER }}
